feat: add monorepo
GuiBibeau/sprout pull request #35
Opened 2024-03-20 18:45 UTC by tobySolutions

## Description of the pull request

This is the pull request to integrate Mono repo support for the bun project. I followed twp resources to achieve this current version in my pull request:

- https://bun.sh/guides/install/workspaces
- https://github.com/colinhacks/bun-workspaces

## Changes made

- Change 1
- Change 2
- ....

## Related issues

## Testings done

## Screenshots (if any)

## Checklist

- [ ] I have written tests
- [ ] My code does not produce new errors
- [ ] I gave myself a code review before asking others.

Please help review @GuiBibeau, @chin-flags

2024-03-20 20:52 UTC, cxalem commented
I wonder if we can use [turborepo](https://turbo.build/) with Bun 🤔

2024-03-20 21:40 UTC, tobySolutions commented
> I wonder if there's a way to use [turborepo](https://turbo.build/) with Bun 🤔

I think we can actually, but, would we be using turborepo to handle the mono-repo support?

2024-03-20 22:31 UTC, cxalem commented
> > I wonder if there's a way to use [turborepo](https://turbo.build/) with Bun 🤔
> 
> I think we can actually, but, would we be using turborepo to handle the mono-repo support?

This is really good, it'll work for now! Turborepo is an option to scale our monorepo, we could implement it later without a problem if we decide it's needed. I would like to know @GuiBibeau and @chin-flags opinions also! 😅

2024-03-20 22:33 UTC, tobySolutions commented
> > > I wonder if there's a way to use [turborepo](https://turbo.build/) with Bun 🤔
> > 
> > 
> > I think we can actually, but, would we be using turborepo to handle the mono-repo support?
> 
> This is working really good already! Turborepo is an option to scale our monorepo, but we could implement it later without a problem if we decide it's needed. I would like to know @GuiBibeau and @chin-flags opinions also! 😅

Yeah, I see your point actually. I'd love to hear their opinions as well.

2024-03-23 09:37 UTC, GuiBibeau requested changes
This if 🔥 🎸 

two  small changes requested:

- Let's `rm -rf .DS_Store` to ensure we don't track the file.
- removing the docker commands and files

2024-03-23 09:37 UTC, GuiBibeau commented on package.json
> +    ]
Let's write some scripts that will call the API scripts so that we don't have to CD down deeper to run the project:

```
"scripts": {
  "api:dev": "cd packages/sprout-server && bun run dev"
}

```

maybe this thread can give insights? https://github.com/oven-sh/bun/issues/2232

2024-03-23 09:37 UTC, GuiBibeau commented on packages/sprout-server/package.json
> +    "dev:db:down": "docker-compose down",
both of these are not in use anymore, let's remove them and the docker files.

2024-03-23 10:20 UTC, tobySolutions commented on package.json
> +    ]
Thanks for the thread by the way! I learned a lot!! I have done this.

2024-03-23 10:22 UTC, tobySolutions commented on packages/sprout-server/package.json
> +    "dev:db:down": "docker-compose down",
I have removed these. Yeah, I don't think we need them anymore actually.

2024-03-23 10:24 UTC, tobySolutions commented
> This if 🔥 🎸
> 
> two small changes requested:
> 
> * Let's `rm -rf .DS_Store` to ensure we don't track the file.
> * removing the docker commands and files

These have been resolved. I removed the file, added the scripts and removed the docker configs.

2024-03-23 10:56 UTC, GuiBibeau approved these changes

2024-03-23 10:56 UTC, merged